name: borg-chart
recipe: lamp
config:
  php: 7.1
  webroot: html
  conf:
    server: config/httpd.conf

services:
  appserver:
    build:
      - "cd $LANDO_MOUNT && composer install"
  cache:
    type: redis
    persist: true

tooling:
  phpunit:
    service: appserver
    cmd: "cd $LANDO_MOUNT && vendor/bin/phpunit"
    description: "Run phpunit tests"
  redis-cli:
    service: cache

